# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wopuam3WNZ0fty8Me6uaPbC658NlrWYO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


# ==========================================
# 1. Load Dataset
# ==========================================
placement_dataset = pd.read_csv("placement.csv")

print("First 5 Rows of Dataset:")
print(placement_dataset.head())

print("\nDataset Information:")
print(placement_dataset.info())


# ==========================================
# 2. Encode Categorical Variables
# ==========================================
category_encoder = LabelEncoder()
categorical_feature_list = placement_dataset.select_dtypes(include='object').columns

for feature_name in categorical_feature_list:
    placement_dataset[feature_name] = category_encoder.fit_transform(
        placement_dataset[feature_name]
    )


# ==========================================
# 3. Visualize Placement Distribution
# ==========================================
plt.figure(figsize=(6, 4))
placement_dataset["status"].value_counts().plot(kind="bar")
plt.title("Placement Status Distribution")
plt.xlabel("Status (0 = Not Placed, 1 = Placed)")
plt.ylabel("Number of Students")
plt.tight_layout()
plt.show()


# ==========================================
# 4. Separate Features and Target
# ==========================================
student_features = placement_dataset.drop("status", axis=1)
placement_target = placement_dataset["status"]


# ==========================================
# 5. Split Data
# ==========================================
training_features, testing_features, training_target, testing_target = train_test_split(
    student_features,
    placement_target,
    test_size=0.25,
    random_state=10
)


# ==========================================
# 6. Scale Features
# ==========================================
feature_standardizer = StandardScaler()

scaled_training_features = feature_standardizer.fit_transform(training_features)
scaled_testing_features = feature_standardizer.transform(testing_features)


# ==========================================
# 7. Train Models
# ==========================================
placement_random_forest = RandomForestClassifier(random_state=10)
placement_random_forest.fit(scaled_training_features, training_target)

placement_decision_tree = DecisionTreeClassifier(random_state=10)
placement_decision_tree.fit(scaled_training_features, training_target)


# ==========================================
# 8. Generate Predictions
# ==========================================
random_forest_predictions = placement_random_forest.predict(scaled_testing_features)
decision_tree_predictions = placement_decision_tree.predict(scaled_testing_features)


# ==========================================
# 9. Evaluate Models
# ==========================================
random_forest_accuracy = accuracy_score(testing_target, random_forest_predictions)
decision_tree_accuracy = accuracy_score(testing_target, decision_tree_predictions)

print("\n===== Random Forest Results =====")
print("Accuracy:", random_forest_accuracy)
print(classification_report(testing_target, random_forest_predictions))

print("\n===== Decision Tree Results =====")
print("Accuracy:", decision_tree_accuracy)
print(classification_report(testing_target, decision_tree_predictions))


# ==========================================
# 10. Confusion Matrix - Random Forest
# ==========================================
rf_confusion_matrix = confusion_matrix(testing_target, random_forest_predictions)

plt.figure(figsize=(6, 4))
sns.heatmap(rf_confusion_matrix, annot=True, fmt='d', cmap="Blues")
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.tight_layout()
plt.show()


# ==========================================
# 11. Feature Importance - Random Forest
# ==========================================
feature_importance_scores = placement_random_forest.feature_importances_
feature_name_list = student_features.columns

feature_importance_table = pd.DataFrame({
    "Feature": feature_name_list,
    "Importance": feature_importance_scores
}).sort_values(by="Importance", ascending=False)

print("\nFeature Importance:")
print(feature_importance_table)

plt.figure(figsize=(10, 5))
plt.bar(feature_importance_table["Feature"], feature_importance_table["Importance"])
plt.xticks(rotation=90)
plt.title("Feature Importance - Random Forest")
plt.xlabel("Features")
plt.ylabel("Importance Score")
plt.tight_layout()
plt.show()


# ==========================================
# 12. Model Accuracy Comparison
# ==========================================
model_names = ["Random Forest", "Decision Tree"]
model_accuracy_scores = [random_forest_accuracy, decision_tree_accuracy]

plt.figure(figsize=(6, 4))
plt.bar(model_names, model_accuracy_scores)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.tight_layout()
plt.show()


# ==========================================
# 13. ROC Curve - Random Forest
# ==========================================
random_forest_probabilities = placement_random_forest.predict_proba(
    scaled_testing_features
)[:, 1]

false_positive_rate, true_positive_rate, roc_thresholds = roc_curve(
    testing_target,
    random_forest_probabilities
)

plt.figure(figsize=(6, 4))
plt.plot(false_positive_rate, true_positive_rate, label="Random Forest ROC")
plt.plot([0, 1], [0, 1], linestyle="--", label="Baseline")
plt.title("ROC Curve - Random Forest")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.tight_layout()
plt.show()

random_forest_roc_auc = roc_auc_score(testing_target, random_forest_probabilities)
print("ROC-AUC Score:", random_forest_roc_auc)